import { json, type RequestHandler } from "@sveltejs/kit";

const SONG_CATEGORIES = [
    // Core Popular Categories
    "Trending Songs",
    "Popular Songs",
    "Global Hits",
    "New Releases",
    "Top Charts",
    "Viral Hits",
    "Rising Artists",
    "Hip Hop Hits",

    // Main Genres
    "Electronic Dance",
    "Rock Classics",
    "Pop Favorites",
    "R&B Soul",
    "Country Music",
    "Jazz Standards",
    "Classical Music",
    "Indie Music",
    "Alternative Rock",
    "Reggae Vibes",
    "Latin Music",
    "K-Pop Hits",
    "Bollywood Music",
    "Afrobeats",
    "Blues Music",
    "Folk Songs",
    "World Music",
    "Ambient Sounds",
    "Instrumental",
    "Acoustic Sessions",
    "Live Performances",
    "Cover Songs",
    "Remixes",
    "80s Classics",
    "90s Nostalgia",
    "2000s Hits",
    "2010s Favorites",

    // Mood & Activity Categories
    "Workout Music",
    "Chill Vibes",
    "Study Music",
    "Party Anthems",
    "Love Songs",
    "Sad Songs",
    "Motivational Music",
    "Gaming Music",
    "Lo-Fi Hip Hop",
    "Synthwave",
    "Reggaeton",
    "Trap Music",
    "House Music",
    "Techno Beats",
    "Dubstep Drops",

    // Decade Categories
    "50s Rock & Roll",
    "60s Psychedelic",
    "70s Disco",
    "80s New Wave",
    "90s Grunge",
    "2000s Pop Punk",
    "2010s EDM",
    "2020s Hits",
    "Retro Synthwave",
    "Vintage Jazz",
    "Classic Soul",
    "Old School Hip Hop",
    "90s R&B",
    "80s Metal",

    // Sub-Genres & Specific Styles
    "Deep House",
    "Progressive House",
    "Future House",
    "Tropical House",
    "Tech House",
    "Minimal Techno",
    "Acid Techno",
    "Drum & Bass",
    "Jungle",
    "Breakbeat",
    "UK Garage",
    "Grime",
    "Drill",
    "Phonk",
    "Wave",
    "Vaporwave",
    "Darkwave",
    "Synthpop",
    "Electropop",
    "Future Bass",
    "Melodic Dubstep",
    "Riddim",
    "Brostep",
    "Glitch Hop",
    "Chillstep",

    // Hip Hop Sub-Genres
    "Old School Rap",
    "Gangsta Rap",
    "Conscious Rap",
    "Boom Bap",
    "Jazz Rap",
    "Cloud Rap",
    "Mumble Rap",
    "Trap Soul",
    "Southern Hip Hop",
    "West Coast Rap",
    "East Coast Rap",
    "UK Drill",
    "French Rap",
    "German Rap",
    "Canadian Hip Hop",

    // Rock Sub-Genres
    "Hard Rock",
    "Heavy Metal",
    "Death Metal",
    "Black Metal",
    "Thrash Metal",
    "Power Metal",
    "Progressive Metal",
    "Doom Metal",
    "Stoner Rock",
    "Post Rock",
    "Math Rock",
    "Indie Rock",
    "Garage Rock",
    "Punk Rock",
    "Pop Punk",
    "Hardcore Punk",
    "Emo",
    "Screamo",
    "Metalcore",
    "Deathcore",
    "Post Hardcore",
    "Alternative Metal",
    "Nu Metal",

    // Electronic Sub-Genres
    "Trance",
    "Progressive Trance",
    "Uplifting Trance",
    "Psytrance",
    "Hardstyle",
    "Hardcore",
    "Gabber",
    "Industrial",
    "EBM",
    "Dark Ambient",
    "Drone",
    "Noise",
    "Glitch",
    "IDM",
    "Breakcore",
    "Speedcore",
    "Happy Hardcore",
    "UK Hardcore",

    // World Music Categories
    "African Music",
    "Asian Music",
    "European Folk",
    "Middle Eastern",
    "Celtic Music",
    "Nordic Folk",
    "Balkan Music",
    "Flamenco",
    "Tango",
    "Salsa",
    "Merengue",
    "Cumbia",
    "Mariachi",
    "Fado",
    "Klezmer",
    "Qawwali",
    "Gamelan",

    // Jazz Sub-Genres
    "Bebop",
    "Cool Jazz",
    "Hard Bop",
    "Free Jazz",
    "Fusion",
    "Smooth Jazz",
    "Acid Jazz",
    "Nu Jazz",
    "Swing",
    "Big Band",
    "Dixieland",
    "Ragtime",
    "Blues Jazz",
    "Latin Jazz",
    "Vocal Jazz",
    "Contemporary Jazz",

    // Classical Categories
    "Baroque",
    "Classical Period",
    "Romantic",
    "Modern Classical",
    "Contemporary Classical",
    "Opera",
    "Symphony",
    "Chamber Music",
    "Piano Music",
    "Violin Music",
    "Orchestral",
    "Choral Music",
    "Sacred Music",
    "Film Scores",

    // Country Sub-Genres
    "Traditional Country",
    "Outlaw Country",
    "Country Pop",
    "Country Rock",
    "Bluegrass",
    "Americana",
    "Alt Country",
    "Honky Tonk",
    "Western Swing",
    "Country Blues",
    "Nashville Sound",
    "Bakersfield Sound",
    "Red Dirt",
    "Texas Country",

    // Reggae & Caribbean
    "Roots Reggae",
    "Dancehall",
    "Dub",
    "Ska",
    "Rocksteady",
    "Reggaeton",
    "Calypso",
    "Soca",
    "Zouk",
    "Kompa",

    // Latin Categories
    "Bachata",
    "Merengue",
    "Salsa",
    "Reggaeton",
    "Latin Pop",
    "Latin Rock",
    "Bossa Nova",
    "Samba",
    "Mambo",
    "Cha Cha",
    "Rumba",
    "Bolero",
    "Vallenato",
    "Cumbia",
    "Mariachi",
    "Norteño",
    "Banda",
    "Ranchera",
    "Tejano",
    "Latin Jazz",

    // Mood-Based Categories
    "Happy Songs",
    "Uplifting Music",
    "Feel Good Hits",
    "Summer Vibes",
    "Beach Music",
    "Road Trip Songs",
    "Coffee Shop",
    "Rainy Day Music",
    "Sunset Songs",
    "Morning Music",
    "Night Drive",
    "Cozy Evening",
    "Nostalgic Hits",
    "Emotional",
    "Peaceful",
    "Energetic",
    "Mellow",
    "Dreamy",
    "Romantic",
    "Heartbreak",
    "Empowering",
    "Inspirational",
    "Meditative",

    // Activity Categories
    "Running Music",
    "Gym Workout",
    "Yoga Music",
    "Meditation",
    "Sleeping Music",
    "Focus Music",
    "Reading Music",
    "Cooking Playlist",
    "Cleaning Songs",
    "Driving Music",
    "Flying Playlist",
    "Walking Music",
    "Dancing",
    "Singing Along",
    "Shower Songs",
    "Car Karaoke",
    "Background Music",
    "Work from Home",
    "Office Playlist",
    "Study Beats",

    // Seasonal Categories
    "Spring Songs",
    "Summer Hits",
    "Autumn Vibes",
    "Winter Music",
    "Christmas Songs",
    "Holiday Music",
    "Halloween",
    "New Year Party",
    "Valentine's Day",
    "Easter Songs",
    "Thanksgiving",
    "Birthday Party",
    "Wedding Songs",

    // Instrument-Focused
    "Guitar Solos",
    "Piano Ballads",
    "Violin Music",
    "Saxophone Jazz",
    "Trumpet Classics",
    "Drum Solos",
    "Bass Lines",
    "Harmonica Blues",
    "Flute Music",
    "Harp Melodies",
    "Banjo Picking",
    "Mandolin",
    "Ukulele Songs",
    "Accordion",

    // Vocal Categories
    "Male Vocals",
    "Female Vocals",
    "Duets",
    "Group Harmony",
    "A Cappella",
    "Choir Music",
    "Opera Singers",
    "Falsetto",
    "Deep Voice",
    "Raspy Voice",
    "Soulful Vocals",
    "Power Vocals",
    "Whisper Singing",
    "Rap Vocals",

    // Language Categories
    "English Songs",
    "Spanish Music",
    "French Songs",
    "German Music",
    "Italian Songs",
    "Portuguese Music",
    "Japanese Songs",
    "Korean Music",
    "Chinese Songs",
    "Hindi Music",
    "Arabic Music",
    "Russian Songs",
    "Dutch Music",
    "Swedish Songs",
    "Norwegian Music",
    "Danish Songs",
    "Finnish Music",
    "Polish Songs",
    "Greek Music",
    "Turkish Songs",

    // Decades Deep Dive
    "1920s Jazz",
    "1930s Swing",
    "1940s Big Band",
    "1950s Doo Wop",
    "1960s Folk",
    "1970s Funk",
    "1980s Synthpop",
    "1990s Alternative",
    "2000s Emo",
    "2010s Dubstep",
    "2020s Drill",
    "Early 2000s Pop",
    "Mid 2000s Rock",
    "Late 2000s Hip Hop",
    "Early 2010s EDM",
    "Mid 2010s Trap",
    "Late 2010s Pop",
    "Early 2020s TikTok",

    // Regional Hip Hop
    "Atlanta Trap",
    "Chicago Drill",
    "Detroit Rap",
    "Memphis Hip Hop",
    "Houston Rap",
    "Miami Bass",
    "Bay Area Rap",
    "Philadelphia Hip Hop",
    "Brooklyn Rap",
    "Queens Hip Hop",
    "Bronx Rap",
    "Long Island Hip Hop",
    "New Jersey Rap",
    "DMV Hip Hop",
    "Carolina Rap",
    "Texas Rap",
    "Louisiana Hip Hop",
    "Florida Rap",
    "Arizona Rap",
    "Colorado Hip Hop",

    // Electronic Micro-Genres
    "Microhouse",
    "Minimal Techno",
    "Deep Techno",
    "Dub Techno",
    "Ambient Techno",
    "Hard Techno",
    "Schranz",
    "Detroit Techno",
    "Berlin Techno",
    "UK Techno",
    "Italian Techno",
    "French Techno",
    "Spanish Techno",
    "Acid House",
    "Chicago House",
    "New York House",
    "UK House",
    "Italian House",
    "French House",
    "German House",

    // Gaming & Nerd Culture
    "Video Game Music",
    "Chiptune",
    "8-bit Music",
    "16-bit Soundtracks",
    "Anime Music",
    "Cartoon Themes",
    "Movie Soundtracks",
    "TV Show Themes",
    "Trailer Music",
    "Epic Music",
    "Cinematic",
    "Orchestral Game Music",
    "Retro Gaming",
    "Modern Gaming OST",
    "Indie Game Music",
    "MMO Soundtracks",
    "Fighting Game Music",

    // Festival & Event Music
    "Festival Anthems",
    "Rave Music",
    "Club Bangers",
    "Underground Hits",
    "Mainstream Dance",
    "Radio Hits",
    "Concert Favorites",
    "Crowd Pleasers",
    "Singalong Songs",
    "Anthem Songs",
    "Stadium Rock",
    "Arena Pop",

    // Time-Based Categories
    "Morning Coffee",
    "Midday Energy",
    "Afternoon Chill",
    "Evening Wind Down",
    "Late Night Vibes",
    "3AM Feels",
    "Dawn Music",
    "Dusk Songs",
    "Midnight Hour",
    "Golden Hour",
    "Blue Hour",
    "Twilight",
    "Sunrise",
    "Sunset",

    // Weather-Based
    "Sunny Day Music",
    "Cloudy Sky Songs",
    "Stormy Weather",
    "Snow Day Playlist",
    "Foggy Morning",
    "Windy Day",
    "Heat Wave Songs",
    "Cool Breeze Music",
    "Hurricane Vibes",
    "Blizzard Beats",
    "Spring Rain",
    "Summer Storm",

    // City & Location Based
    "New York Hip Hop",
    "LA Pop",
    "Chicago House",
    "Detroit Techno",
    "Atlanta Trap",
    "Nashville Country",
    "Seattle Grunge",
    "San Francisco Psychedelic",
    "Boston Rock",
    "Philadelphia Soul",
    "Memphis Blues",
    "New Orleans Jazz",
    "Austin Indie",
    "Portland Alternative",
    "Miami Bass",
    "London Punk",
    "Manchester Indie",
    "Liverpool Beat",
    "Berlin Techno",
    "Paris House",
    "Tokyo Electronic",
    "Seoul K-Pop",
    "Mumbai Bollywood",

    // Social Media Era
    "TikTok Hits",
    "Instagram Worthy",
    "YouTube Viral",
    "Snapchat Songs",
    "Twitter Trending",
    "Spotify Viral",
    "Apple Music Charts",
    "SoundCloud Gems",
    "Bandcamp Finds",
    "Beatport Top",
    "Shazam Most Searched",

    // Streaming Era Categories
    "Playlist Starters",
    "Shuffle Ready",
    "Background Beats",
    "Commute Music",
    "Homework Help",
    "Coding Music",
    "Creative Work",
    "Brainstorming Beats",
    "Deadline Rush",
    "Project Music",
    "Meeting Background",

    // Generational Categories
    "Gen Z Anthems",
    "Millennial Nostalgia",
    "Gen X Classics",
    "Boomer Favorites",
    "Gen Alpha Rising",
    "90s Kids",
    "2000s Babies",
    "2010s Teens",
    "COVID Era Music",
    "Quarantine Hits",
    "Lockdown Vibes",
    "Remote Work Songs",

    // Technology Era
    "Dial-Up Days",
    "Broadband Beats",
    "WiFi Era",
    "5G Songs",
    "Streaming Age",
    "Digital Native",
    "Cloud Music",
    "AI Generated",
    "Algorithm Picks",
    "Human Curated",
    "Machine Learning",
    "Data Driven",
    "Trend Following",

    // Micro-Genres & Internet Culture
    "Bedroom Pop",
    "Dream Pop",
    "Shoegaze",
    "Post-Rock",
    "Post-Punk",
    "No Wave",
    "Noise Rock",
    "Krautrock",
    "Psych Rock",
    "Garage Punk",
    "Surf Rock",
    "Yacht Rock",
    "Soft Rock",
    "Arena Rock",
    "Progressive Rock",
    "Symphonic Rock",
    "Folk Rock",
    "Country Rock",
    "Southern Rock",
    "Heartland Rock",
    "Jangle Pop",
    "Power Pop",

    // Experimental & Avant-Garde
    "Experimental",
    "Avant-Garde",
    "Abstract",
    "Conceptual",
    "Sound Art",
    "Musique Concrète",
    "Acousmatic",
    "Electroacoustic",
    "Live Electronics",
    "Computer Music",
    "Algorithmic",
    "Generative",
    "Interactive",
    "Installation",
    "Performance Art",
    "Multimedia",
    "Cross-Media",
    "Interdisciplinary",

    // Religious & Spiritual
    "Gospel",
    "Contemporary Christian",
    "Praise & Worship",
    "Hymns",
    "Spiritual Jazz",
    "Sacred Music",
    "Devotional",
    "Chanting",
    "Mantras",
    "Kirtan",
    "Bhajans",
    "Qawwali",
    "Sufi Music",
    "Buddhist Chants",
    "Gregorian Chant",
    "Orthodox Chant",
    "Jewish Music",
    "Islamic Music",
    "Hindu Music",
    "Sikh Music",

    // Cultural Movements
    "Counterculture",
    "Underground",
    "Alternative Scene",
    "Indie Scene",
    "DIY Culture",
    "Punk Movement",
    "Hip Hop Culture",
    "Rave Culture",
    "Club Scene",
    "Festival Circuit",
    "College Radio",
    "Pirate Radio",
    "Mixtape Culture",
    "Cassette Culture",
    "Vinyl Revival",
    "CD Era",
    "MP3 Revolution",
    "Streaming Era",

    // Production Styles
    "Lo-Fi Production",
    "Hi-Fi Quality",
    "Analog Sound",
    "Digital Clean",
    "Tape Saturation",
    "Vinyl Warmth",
    "Studio Polish",
    "Live Recording",
    "Field Recording",
    "Ambient Recording",
    "Binaural",
    "Surround Sound",
    "Spatial Audio",
    "3D Audio",
    "Immersive",
    "Headphone Mix",
    "Speaker Optimized",
    "Car Audio",

    // Collaborative Categories
    "Collaborations",
    "Featured Artists",
    "Producer Showcases",
    "Songwriter Spotlights",
    "Session Musicians",
    "Band Efforts",
    "Solo Projects",
    "Side Projects",
    "Supergroups",
    "One-Hit Wonders",
    "Comeback Singles",
    "Debut Albums",
    "Final Albums",
    "Greatest Hits",
    "Deep Cuts",
    "B-Sides",
    "Rarities",
    "Unreleased",

    // Format-Based
    "Single Releases",
    "Album Tracks",
    "EP Collections",
    "Mixtape Cuts",
    "Compilation Hits",
    "Soundtrack Songs",
    "Demo Versions",
    "Acoustic Versions",
    "Unplugged",
    "MTV Unplugged",
    "Live Versions",
    "Radio Edits",
    "Extended Versions",
    "Remixes",
    "Mashups",
    "Bootlegs",
    "Official Releases",
    "Leaks",
    "Previews",

    // Chart Performance
    "Number One Hits",
    "Top 10 Songs",
    "Chart Climbers",
    "Sleeper Hits",
    "Viral Sensations",
    "Underground Favorites",
    "Critical Darlings",
    "Commercial Success",
    "Cult Classics",
    "Hidden Gems",
    "Overlooked Tracks",
    "Rediscovered",

    // Emotional Depth Categories
    "Melancholic",
    "Euphoric",
    "Aggressive",
    "Peaceful",
    "Anxious",
    "Confident",
    "Vulnerable",
    "Powerful",
    "Delicate",
    "Raw",
    "Polished",
    "Gritty",
    "Smooth",
    "Rough",
    "Elegant",
    "Primitive",
    "Sophisticated",
    "Simple",
    "Complex",
    "Minimalist",
    "Maximalist",
    "Sparse",
    "Dense",
    "Light",
    "Heavy",
    "Bright",
    "Dark",

    // Extended Regional Categories
    "Scandinavian Pop",
    "Eastern European Folk",
    "Balkan Beats",
    "Mediterranean Vibes",
    "Alpine Music",
    "Arctic Sounds",
    "Tropical Rhythms",
    "Desert Blues",
    "Mountain Music",
    "Ocean Songs",
    "Forest Ambience",
    "Urban Beats",
    "Rural Melodies",
    "Suburban Sounds",
    "Highway Music",
    "Underground Railroad",

    // Time Period Micro-Categories
    "Early Beatles Era",
    "British Invasion",
    "Summer of Love",
    "Woodstock Era",
    "Disco Fever",
    "MTV Generation",
    "Grunge Explosion",
    "Britpop Wave",
    "Nu Metal Rise",
    "Emo Revival",
    "Indie Sleaze",
    "Blog House",
    "Dubstep Boom",
    "Trap Takeover",
    "Bedroom Pop Rise",
    "Hyperpop Emergence",
    "Drill Evolution",

    // Instrumental Focus Extended
    "Synthesizer Showcase",
    "Drum Machine Beats",
    "Sample-Based",
    "Live Instruments",
    "Orchestra",
    "String Quartet",
    "Brass Section",
    "Woodwinds",
    "Percussion",
    "Electronic Manipulation",
    "Sound Design",
    "Foley Integration",
    "Nature Sounds",
    "Urban Soundscape",
    "Industrial Noise",
    "Mechanical Rhythms",
    "Organic Textures",

    // Venue-Specific
    "Stadium Anthems",
    "Arena Rock",
    "Club Bangers",
    "Intimate Venue",
    "Coffee Shop",
    "Bar Music",
    "Restaurant Background",
    "Hotel Lobby",
    "Elevator Music",
    "Shopping Mall",
    "Airport Lounge",
    "Spa Music",
    "Gallery Opening",
    "Museum Audio",
    "Library Quiet",
    "Bookstore Browse",

    // Professional Use
    "Background Score",
    "Jingle Music",
    "Commercial Music",
    "Podcast Intro",
    "YouTube Background",
    "Twitch Stream",
    "Corporate Video",
    "Wedding Music",
    "Funeral Music",
    "Meditation Guide",
    "Therapy Session",
    "Workout Class",
    "Yoga Flow",
    "Dance Class",
    "Aerobics",
    "Spinning Class",

    // Extended Mood Categories
    "Contemplative",
    "Reflective",
    "Introspective",
    "Extroverted",
    "Social",
    "Isolated",
    "Connected",
    "Disconnected",
    "Grounded",
    "Elevated",
    "Centered",
    "Scattered",
    "Focused",
    "Distracted",
    "Present",
    "Nostalgic",
    "Future-Focused",
    "Timeless",
    "Temporal",
    "Eternal",
    "Momentary",

    // Advanced Electronic Sub-Genres
    "Neurofunk",
    "Liquid DnB",
    "Jump Up",
    "Ragga Jungle",
    "Intelligent DnB",
    "Hardstep",
    "Darkstep",
    "Techstep",
    "Sambass",
    "Jazzstep",
    "Atmospheric DnB",
    "Minimal DnB",
    "Dancefloor DnB",
    "Experimental Bass",
    "Halftime",
    "Footwork",
    "Juke",
    "Ghetto House",
    "Booty Bass",
    "Electro Bass",

    // Vocal Technique Categories
    "Vibrato Heavy",
    "Straight Tone",
    "Breathy Vocals",
    "Belting",
    "Mixed Voice",
    "Head Voice",
    "Chest Voice",
    "Vocal Fry",
    "Melisma",
    "Vocal Runs",
    "Harmonies",
    "Call and Response",
    "Spoken Word",
    "Rap Flow",
    "Melodic Rap",
    "Sung Rap",
    "Auto-Tuned",
    "Pitch Corrected",

    // Production Technique
    "Sidechain Compression",
    "Reverb Heavy",
    "Dry Mix",
    "Analog Warmth",
    "Digital Precision",
    "Tape Delay",
    "Spring Reverb",
    "Plate Reverb",
    "Hall Reverb",
    "Room Sound",
    "Close Mic",
    "Distant Mic",
    "Compressed",
    "Dynamic Range",
    "Loud Master",
    "Quiet Dynamics",

    // Cultural Heritage
    "Traditional Folk",
    "Contemporary Folk",
    "Neo-Folk",
    "Dark Folk",
    "Freak Folk",
    "Indie Folk",
    "Chamber Folk",
    "Psych Folk",
    "Folk Punk",
    "Folk Metal",
    "Folk Pop",
    "Singer-Songwriter",
    "Troubadour",
    "Minstrel",
    "Ballad Singer",
    "Story Songs",
    "Narrative Music",
    "Concept Albums",

    // Extended World Music
    "Tuvan Throat Singing",
    "Mongolian Folk",
    "Tibetan Chants",
    "Indian Classical",
    "Pakistani Qawwali",
    "Indonesian Gamelan",
    "Thai Traditional",
    "Vietnamese Folk",
    "Japanese Taiko",
    "Chinese Guqin",
    "Korean Pansori",
    "African Drums",
    "West African Griot",
    "Ethiopian Jazz",
    "South African Gospel",
    "Aboriginal Didgeridoo",
    "Native American Flute",
    "Inuit Throat Singing",
    "Celtic Harp",

    // Dance Categories Extended
    "Breakdancing Music",
    "Popping Beats",
    "Locking Grooves",
    "Krumping Tracks",
    "Voguing Music",
    "Ballroom Dance",
    "Tango Music",
    "Waltz",
    "Foxtrot",
    "Quickstep",
    "Swing Dance",
    "Lindy Hop",
    "Charleston",
    "Jive",
    "Rumba",
    "Cha-Cha-Cha",
    "Samba",
    "Paso Doble",
    "Salsa Dancing",

    // Extended Gaming Categories
    "RPG Soundtracks",
    "FPS Music",
    "Racing Game Beats",
    "Fighting Game Themes",
    "Puzzle Game Music",
    "Horror Game Audio",
    "Adventure Game Music",
    "Platformer Beats",
    "Strategy Game Music",
    "Simulation Game Audio",
    "Sports Game Music",
    "Rhythm Game Tracks",
    "VR Game Audio",

    // Streaming Platform Specific
    "Spotify Discover Weekly",
    "Apple Music New",
    "YouTube Music Mix",
    "Amazon Music Prime",
    "Tidal Masters",
    "Deezer Flow",
    "Pandora Radio",
    "SoundCloud Next",
    "Bandcamp Friday",
    "Beatport Hype",
    "Juno Download",
    "Traxsource Essentials",
    "iTunes Charts",
    "Google Play Music",

    // Social Context Extended
    "First Date Music",
    "Anniversary Songs",
    "Breakup Playlist",
    "Moving On Music",
    "New Relationship",
    "Long Distance Love",
    "Friends Hangout",
    "Family Gathering",
    "Holiday Party",
    "Office Party",
    "Graduation Songs",
    "Retirement Party",
    "Housewarming",
    "Baby Shower",
    "Gender Reveal",

    // Extended Seasonal
    "Early Spring",
    "Late Spring",
    "Early Summer",
    "Mid Summer",
    "Late Summer",
    "Early Fall",
    "Mid Fall",
    "Late Fall",
    "Early Winter",
    "Mid Winter",
    "Late Winter",
    "Seasonal Transition",
    "Daylight Saving",
    "Longest Day",
    "Shortest Day",
    "Equinox",
    "Solstice",
    "Harvest Time",

    // Extended Activity Categories
    "Deep Work",
    "Creative Flow",
    "Problem Solving",
    "Brainstorming",
    "Team Building",
    "Networking",
    "Public Speaking",
    "Presentation",
    "Interview Prep",
    "Job Search",
    "Career Change",
    "Retirement",
    "Life Transition",
    "Moving Houses",
    "New City",
    "Travel Planning",
    "Packing",
    "Unpacking",

    // Extended Emotional Granularity
    "Bittersweet",
    "Wistful",
    "Yearning",
    "Longing",
    "Content",
    "Satisfied",
    "Fulfilled",
    "Empty",
    "Hollow",
    "Rich",
    "Full",
    "Abundant",
    "Scarce",
    "Grateful",
    "Ungrateful",
    "Appreciative",
    "Dismissive",
    "Accepting",
    "Resistant",
    "Open",
    "Closed",
    "Vulnerable",
    "Guarded",
    "Trusting",

    // Micro-Regional Scenes
    "Brooklyn Indie",
    "Portland Indie",
    "Austin SXSW",
    "Nashville Alt Country",
    "Richmond VA Scene",
    "Chapel Hill Indie",
    "Athens GA Rock",
    "Minneapolis Prince",
    "Seattle Coffee Shop",
    "San Francisco Psychedelic",
    "LA Sunset Strip",
    "Detroit Underground",
    "Chicago Deep House",
    "Miami Beach",
    "New Orleans Second Line",

    // Extended Production Eras
    "Analog Era",
    "Digital Era",
    "Hybrid Era",
    "Laptop Era",
    "Mobile Era",
    "Cloud Era",
    "AI Era",
    "Home Studio",
    "Bedroom Producer",
    "Garage Band",
    "Professional Studio",
    "Abbey Road Sound",
    "Motown Sound",
    "Phil Spector Wall",
    "Quincy Jones Production",
    "Rick Rubin Minimalism",

    // Extended Cultural Movements
    "Beat Generation",
    "Hippie Movement",
    "Punk Rebellion",
    "New Romantic",
    "New Jack Swing",
    "Britpop Revival",
    "Nu Soul",
    "Neo Soul",
    "Alternative R&B",
    "Post-Internet",
    "Seapunk",
    "Vaporwave Aesthetic",
    "Cottagecore",
    "Dark Academia",
    "Light Academia",
    "Goblincore",

    // Extended Format Categories
    "7-inch Singles",
    "12-inch Maxi",
    "Cassette Culture",
    "CD Singles",
    "DVD Audio",
    "SACD",
    "Vinyl Revival",
    "Limited Edition",
    "Picture Disc",
    "Colored Vinyl",
    "Bootleg Pressing",
    "Test Pressing",
    "White Label",
    "Promo Copy",
    "Radio Promo",
    "DJ Only",
    "Club Promo",

    // Technology Integration
    "Spatial Audio",
    "Dolby Atmos",
    "Binaural Beats",
    "432 Hz Tuning",
    "440 Hz Standard",
    "High Resolution",
    "Lossless Audio",
    "Compressed Audio",
    "Streaming Quality",
    "Vinyl Rip",
    "Tape Transfer",
    "Digital Remaster",
    "AI Remaster",
    "Stem Separation",
    "Karaoke Version",

    // Extended Collaborative
    "Producer Tags",
    "Engineer Credits",
    "Mixer Showcase",
    "Mastering Engineer",
    "Session Player",
    "Ghost Writer",
    "Co-Writer",
    "Sample Flip",
    "Interpolation",
    "Cover Version",
    "Tribute Song",
    "Parody Version",
    "Acoustic Cover",
    "Electronic Remix",
    "Orchestra Cover",
    "Jazz Version",

    // Extended Chart Categories
    "Billboard Hot 100",
    "Alternative Charts",
    "Dance Charts",
    "R&B Charts",
    "Country Charts",
    "Rock Charts",
    "Rap Charts",
    "Latin Charts",
    "World Charts",
    "Jazz Charts",
    "Classical Charts",
    "Holiday Charts",
    "Viral Charts",
    "Emerging Artists",
    "Comeback Chart",
    "Crossover Hit",

    // Extended Emotional Depth
    "Cathartic",
    "Purging",
    "Cleansing",
    "Healing",
    "Transformative",
    "Revelatory",
    "Awakening",
    "Consciousness Expanding",
    "Mind Opening",
    "Heart Opening",
    "Soul Stirring",
    "Spirit Lifting",
    "Energy Clearing",
    "Chakra Balancing",
    "Frequency Healing",
    "Vibrational Medicine",

    // Final Extended Categories
    "Quantum Music",
    "Fractal Compositions",
    "Mathematical Music",
    "Golden Ratio",
    "Fibonacci Sequence",
    "Chaos Theory",
    "Emergence",
    "Complex Systems",
    "Artificial Intelligence",
    "Machine Learning",
    "Neural Networks",
    "Deep Learning",
    "Algorithmic Composition",
    "Generative Art",
    "Interactive Media",
    "Responsive Music",
    "Adaptive Audio",
    "Environmental Sensing",
    "Biometric Response",
    "Emotional AI",

    // Ultimate Extended Collection
    "Microscopic Genres",
    "Nano Categories",
    "Quantum Classifications",
    "Dimensional Music",
    "Parallel Universe Sounds",
    "Alternative Timeline Beats",
    "Multiverse Harmonies",
    "Infinite Playlist",
    "Endless Categories",
    "Boundless Music",
    "Limitless Sounds",
    "Eternal Rhythms",
    "Cosmic Frequencies",
    "Universal Vibrations",
    "Galactic Grooves",
    "Interstellar Melodies",
    "Space-Time Continuum",
    "Reality Bending Beats",
    "Consciousness Altering",
    "Transcendent Audio",
    "Enlightened Listening",
];

export const GET: RequestHandler = async ({ locals, url }) => {
    const offset = parseInt(url.searchParams.get("offset") || "0");
    const limit = parseInt(url.searchParams.get("limit") || "8");
    if (!locals.ytmusic) {
        return json({ error: "Music service unavailable" }, { status: 503 });
    }
    // Get the next batch of categories
    const categories = SONG_CATEGORIES.slice(offset, offset + limit);
    if (categories.length === 0) {
        return json({ categories: {}, hasMore: false });
    }
    // Create and await promises for each category in parallel
    const songs: Record<string, any> = {};
    try {
        // Process all categories in parallel for better performance
        const promises = categories.map(async (category) => {
            try {
                const result = await locals.ytmusic.searchSongs(category);
                return { category, result };
            } catch (error) {
                console.error(`Failed to fetch songs for category ${category}:`, error);
                return { category, result: [] };
            }
        });
        const results = await Promise.all(promises);
        // Build the songs object from results
        results.forEach(({ category, result }) => {
            songs[category] = result;
        });
    } catch (error) {
        console.error("Error processing categories:", error);
        // Return empty results on error
        categories.forEach((category) => {
            songs[category] = [];
        });
    }
    return json({
        categories: songs,
        hasMore: offset + limit < SONG_CATEGORIES.length,
        total: SONG_CATEGORIES.length,
    });
};
